# Workflow that is using reusable workflow
name: After

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.get-message.outputs.message }}
    steps:
      - name: First step
        id: get-message
        run: |
          echo "This is the first job"
          echo "message=First things first" >> $GITHUB_OUTPUT

  build:
    needs: first
    uses: ./.github/workflows/reusable-build.yml
    with:
      message: ${{ needs.first.outputs.message }}

  summary:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print build result
        run: echo ${{ needs.build.outputs.result }}
