# Reusable build workflow
name: Reusable Build

on:
    workflow_call:
        inputs:
            message:
                description: Message from the first job
                required: true
                type: string
        secrets:
            shush:
                description: A secret
                required: true
            maybe-secret:
                description: An optional secret
                required: true

        outputs:
            result:
                description: Result from the build job
                value: ${{ jobs.build.outputs.result }}

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.set-result.outputs.result }}

        steps:
            - name: First job message
              run: echo ${{ inputs.message }}

            - name: Use secrets
              run: |
                  echo "Using secrets: ${{ secrets.shush }}"

                  echo "Using maybe-secret: ${{ inputs.maybe-secret }}"

            - name: Set result
              id: set-result
              run: echo "result=Build complete" >> $GITHUB_OUTPUT
